// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeridocX.Server.Data;

#nullable disable

namespace VeridocX.Server.Migrations
{
    [DbContext(typeof(VeridocXDbContext))]
    [Migration("20260627151037_AddAffordabilityAssessments")]
    partial class AddAffordabilityAssessments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeridocX.Server.Domain.Affordability.AffordabilityAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DeclaredBelowNorm")
                        .HasColumnType("boolean")
                        .HasColumnName("declared_below_norm");

                    b.Property<decimal>("DiscretionaryIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discretionary_income");

                    b.Property<decimal>("GrossMonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_monthly_income");

                    b.Property<bool>("IsAffordable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_affordable");

                    b.Property<decimal>("ProposedInstalment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("proposed_instalment");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("SubjectFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subject_fingerprint");

                    b.HasKey("Id")
                        .HasName("pk_affordability_assessments");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_affordability_assessments_created_at");

                    b.HasIndex("SubjectFingerprint")
                        .HasDatabaseName("ix_affordability_assessments_subject_fingerprint");

                    b.ToTable("affordability_assessments", (string)null);
                });

            modelBuilder.Entity("VeridocX.Server.Domain.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobRef")
                        .HasColumnType("text")
                        .HasColumnName("blob_ref");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("text")
                        .HasColumnName("callback_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_type");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pipeline_version");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("Fingerprint")
                        .HasDatabaseName("ix_jobs_fingerprint");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_jobs_status_created_at");

                    b.ToTable("jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
